services:
  - type: web
    name: cult-staking-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: REACT_APP_XAMAN_API_KEY
        sync: false
      - key: REACT_APP_XAMAN_API_SECRET
        sync: false 